"use strict";
// Defaults seeded ONCE from the Simba Technology Hub Operations Manual. After seeding, management edits
// offices, responsibilities, KPIs, targets, weights and scoring settings in the app (no code changes needed).

// KPI row: [name, measurement_type, target, auto_source|null, weight, frequency]
const Q = (name) => [name, "QUALITY", 8, null, 10, "MONTHLY"]; // management rating 1-10, 8+ = full marks
const QO = (name) => [name, "RATING_10", 7, null, 10, "QUARTERLY"]; // quarterly objectives rating
const TIME = (name, target = 90, auto = "TASK_ON_TIME", w = 15) => [name, "DEADLINE", target, auto, w, "MONTHLY"];

const OFFICES = [
  {
    code: "TECH_OPS", name: "Tech Operations Manager", short: "Tech Ops",
    purpose: "Oversee technical operations, training programs, technical personnel, infrastructure, and technology-related projects.",
    responsibilities: [
      "Oversee all technical operations and training programs.",
      "Coordinate technical projects and ensure timely delivery.",
      "Manage instructors, developers, and technical volunteers.",
      "Maintain laboratories, internet infrastructure, hardware, and software.",
      "Provide technical support during events and training programs.",
      "Coordinate technical setup for workshops, exhibitions, hackathons, and other programs.",
      "Monitor the quality of technical programs and curriculum delivery.",
      "Support innovation projects and prototype development.",
      "Maintain technical documentation and operational reports.",
      "Manage technical assets and equipment inventory.",
      "Develop and enforce technical SOPs, safety procedures, and operational standards.",
    ],
    kpis: [
      TIME("Timely execution of technical responsibilities"),
      Q("Quality of technical deliverables"),
      Q("Effective management of instructors and technical personnel"),
      Q("Training program performance"),
      ["Technical infrastructure availability and maintenance", "PERCENTAGE", 95, null, 10, "MONTHLY"],
      Q("Proper management of technical assets"),
      QO("Achievement of quarterly objectives"),
      Q("Effective collaboration with other offices"),
      Q("Contribution to hub growth"),
    ],
  },
  {
    code: "ORPI", name: "Research, Partnerships & Innovation (ORPI)", short: "ORPI",
    purpose: "Identify opportunities, develop strategic partnerships, coordinate research activities, and drive innovation initiatives.",
    responsibilities: [
      "Conduct research on technology trends and ecosystem opportunities.",
      "Develop partnerships with universities, companies, NGOs, government institutions, and other organizations.",
      "Identify grants, sponsorships, funding opportunities, and strategic programs.",
      "Prepare proposals and partnership agreements.",
      "Coordinate research and innovation initiatives.",
      "Scout fellowships, competitions, grants, and accelerator programs.",
      "Support startups and members of the hub in accessing external opportunities.",
      "Manage partner relationships and collaboration activities.",
      "Measure partnership impact and produce reports.",
      "Represent the hub at relevant networking and partnership events.",
      "Develop long-term innovation and partnership strategies.",
    ],
    kpis: [
      ["Number and quality of strategic partnerships developed", "NUMBER", 1, null, 10, "MONTHLY"],
      ["Funding and sponsorship opportunities identified", "NUMBER", 2, null, 10, "MONTHLY"],
      ["Proposals submitted and successful outcomes", "NUMBER", 1, null, 10, "MONTHLY"],
      ["Research and innovation initiatives completed", "NUMBER", 1, null, 10, "MONTHLY"],
      ["External opportunities secured for the hub", "NUMBER", 1, null, 10, "MONTHLY"],
      Q("Quality of partner relationship management"),
      QO("Achievement of quarterly objectives"),
      Q("Effective collaboration"),
      Q("Contribution to hub growth"),
    ],
  },
  {
    code: "CREATIVE_DIRECTOR", name: "Creative Director", short: "Creative",
    purpose: "Provide creative leadership and maintain the organization's visual identity, brand standards, and creative direction.",
    responsibilities: [
      "Lead the creative vision of the hub.",
      "Manage branding and visual identity.",
      "Supervise graphic design and multimedia production.",
      "Review and approve creative materials before publication.",
      "Develop concepts for campaigns, programs, events, and promotions.",
      "Coordinate creative team activities.",
      "Maintain brand consistency across all platforms and materials.",
      "Support marketing initiatives with appropriate creative assets.",
      "Guide photographers, videographers, designers, and other creative personnel.",
      "Mentor and develop creative team members.",
      "Evaluate creative performance and quality.",
    ],
    kpis: [
      Q("Quality of creative deliverables"),
      Q("Brand consistency"),
      TIME("Timely delivery of creative materials"),
      Q("Effectiveness of campaign concepts"),
      Q("Creative team productivity"),
      Q("Quality control and approval turnaround"),
      QO("Achievement of quarterly creative objectives"),
      Q("Effective collaboration"),
      Q("Contribution to brand growth and visibility"),
    ],
  },
  {
    code: "CONTENT_CREATOR", name: "Content Creator", short: "Content",
    purpose: "Produce engaging, educational, promotional, and informative content communicating the activities, programs, achievements, and identity of the hub.",
    responsibilities: [
      "Create engaging content for digital platforms.",
      "Cover events and activities through photographs and videos.",
      "Write captions, articles, blogs, stories, and other content.",
      "Develop weekly content calendars.",
      "Produce educational and promotional content.",
      "Edit videos, images, and graphics where required.",
      "Document success stories, testimonials, and organizational achievements.",
      "Work closely with the Creative Director.",
      "Track content performance.",
      "Maintain organized content archives.",
      "Support community engagement through relevant content.",
    ],
    kpis: [
      ["Quantity and quality of content produced", "NUMBER", 12, null, 10, "MONTHLY"],
      TIME("Timely delivery of content", 95),
      ["Adherence to the approved content calendar", "PERCENTAGE", 90, null, 10, "MONTHLY"],
      Q("Quality of event documentation"),
      Q("Content engagement and performance"),
      Q("Consistency with brand standards"),
      Q("Effective collaboration with the Creative Director and Social Media & Community Manager"),
      QO("Achievement of quarterly content objectives"),
      Q("Contribution to hub visibility and growth"),
    ],
  },
  {
    code: "PROJECT_MANAGER", name: "Project Manager", short: "Projects",
    purpose: "Coordinate projects, monitor implementation, ensure accountability, and facilitate timely delivery of organizational initiatives.",
    responsibilities: [
      "Plan and coordinate projects from initiation to completion.",
      "Develop project timelines, milestones, deliverables, and implementation plans.",
      "Coordinate activities across departments and project teams.",
      "Track project progress, deadlines, and assigned responsibilities.",
      "Follow up with team members and departments on outstanding tasks.",
      "Identify project delays, risks, and operational challenges and escalate them appropriately.",
      "Maintain project plans, documentation, records, and reports.",
      "Organize project meetings and coordinate project-related communication.",
      "Monitor project deliverables to ensure they meet approved requirements and standards.",
      "Prepare regular project progress and status reports for management.",
      "Ensure proper documentation of project decisions, actions, and outcomes.",
      "Coordinate the implementation of strategic projects and organizational initiatives.",
      "Monitor the use of project resources and ensure responsible utilization.",
      "Evaluate completed projects and document lessons learned.",
      "Ensure accountability and timely completion of project responsibilities.",
    ],
    kpis: [
      ["Percentage of projects completed on schedule", "PERCENTAGE", 85, null, 10, "MONTHLY"],
      TIME("Percentage of milestones achieved on time", 90, "TASK_ON_TIME", 10),
      Q("Quality of project deliverables"),
      ["Project completion rate", "COMPLETION_RATE", 90, "TASK_COMPLETION", 10, "MONTHLY"],
      Q("Timely identification and escalation of project risks"),
      Q("Accuracy and consistency of project reports"),
      Q("Team accountability and task completion"),
      Q("Effective inter-office coordination"),
      ["Achievement of project objectives", "RATING_10", 7, null, 10, "MONTHLY"],
      Q("Contribution to organizational growth"),
    ],
  },
  {
    code: "PERSONAL_ASSISTANT", name: "Personal Assistant", short: "PA",
    purpose: "Provide the Managing Director and executive management with administrative, scheduling, communication, coordination, and organizational support.",
    responsibilities: [
      "Manage the Managing Director's schedule, appointments, and meetings.",
      "Coordinate and organize executive meetings and engagements.",
      "Prepare meeting agendas, documents, and materials as required.",
      "Record, organize, and distribute meeting minutes and action points.",
      "Follow up on instructions and assignments delegated by the Managing Director.",
      "Coordinate communication between the Managing Director and relevant offices, staff, partners, and stakeholders.",
      "Maintain organized executive records, documents, correspondence, and schedules.",
      "Prepare and organize reports, briefs, presentations, and official correspondence as directed.",
      "Manage administrative logistics for executive meetings, events, and engagements.",
      "Monitor important deadlines, appointments, and commitments of the Managing Director.",
      "Assist in coordinating official visits, appointments, and external engagements.",
      "Maintain confidentiality of sensitive executive and organizational information.",
      "Support the Managing Director in monitoring priority organizational matters.",
      "Ensure executive instructions requiring follow-up are properly communicated and tracked.",
      "Provide general administrative support to the Managing Director and executive management.",
    ],
    kpis: [
      Q("Effective management of executive schedules"),
      TIME("Timely completion of assigned executive tasks", 95),
      Q("Accuracy of meeting records and documentation"),
      Q("Timely follow-up on executive instructions"),
      Q("Effective communication and coordination"),
      Q("Proper organization of executive documents"),
      Q("Confidentiality and professional handling of information"),
      TIME("Timely preparation of required reports and materials", 90, "REPORTS_ON_TIME", 10),
      Q("Efficient administrative support"),
      Q("Contribution to effective executive operations"),
    ],
  },
  {
    code: "SOCIAL_MEDIA", name: "Social Media & Community Manager", short: "Social",
    purpose: "Manage the organization's social media presence, grow its digital and physical communities, promote programs and initiatives, and maintain meaningful engagement with students, partners, followers, and other stakeholders.",
    responsibilities: [
      "Develop and implement social media and community engagement strategies.",
      "Manage Simba Technology Hub's official social media platforms and online communities.",
      "Develop and maintain weekly and monthly social media schedules.",
      "Publish approved content across relevant social media platforms.",
      "Monitor comments, messages, inquiries, mentions, and community interactions.",
      "Respond to community members and social media inquiries professionally and promptly.",
      "Promote Simba Technology Hub programs, training, events, campaigns, and initiatives.",
      "Work closely with the Creative Director and Content Creator to coordinate social media content.",
      "Grow and maintain an active and engaged online community.",
      "Coordinate online and offline community activities, discussions, campaigns, and engagement initiatives.",
      "Coordinate and support student ambassadors, volunteers, and community representatives.",
      "Monitor social media analytics, audience growth, reach, engagement, and other performance indicators.",
      "Collect feedback from students, followers, community members, and stakeholders.",
      "Identify opportunities for increased audience engagement, visibility, partnerships, and community growth.",
      "Maintain accurate records of social media campaigns, community activities, and engagement data.",
      "Prepare weekly and monthly social media and community management reports.",
      "Ensure all published communication follows Simba Technology Hub's approved brand and communication standards.",
      "Escalate sensitive complaints, reputational issues, and matters requiring management attention.",
      "Support the communication of organizational announcements and important updates.",
      "Build positive relationships between Simba Technology Hub and its digital and physical communities.",
    ],
    kpis: [
      ["Social media audience growth", "PERCENTAGE", 5, null, 10, "MONTHLY"],
      ["Social media engagement rate", "PERCENTAGE", 4, null, 10, "MONTHLY"],
      ["Reach and visibility of published content", "PERCENTAGE", 100, null, 10, "MONTHLY"],
      TIME("Timely publication of approved content", 90, "TASK_ON_TIME", 10),
      ["Response time to messages and community inquiries", "PERCENTAGE", 90, null, 10, "MONTHLY"],
      Q("Growth and activity of online and offline communities"),
      Q("Event and program promotion performance"),
      Q("Quality and consistency of online communication"),
      Q("Community satisfaction and feedback"),
      ["Achievement of monthly social media objectives", "RATING_10", 7, null, 10, "MONTHLY"],
      TIME("Accuracy and timeliness of performance reports", 90, "REPORTS_ON_TIME", 10),
      Q("Contribution to Simba Technology Hub's brand visibility and growth"),
    ],
  },
];

const GENERAL_STANDARD = [
  "Timely execution of assigned responsibilities", "High quality of deliverables", "Accountability for assigned duties",
  "Effective communication and collaboration", "Proper documentation and reporting", "Professional conduct",
  "Achievement of monthly and quarterly objectives", "Compliance with Simba Technology Hub policies and operational standards",
  "Initiative and problem-solving", "Measurable contribution to the growth of Simba Technology Hub",
];

const DEFAULT_SETTINGS = {
  weights: { task: 30, kpi: 30, attendance: 15, reports: 10, productivity: 10, teamwork: 5 },
  // pay_pct = share of base salary recommended in this band. Edit in Office KPIs > Scoring settings.
  bands: [
    { key: "CRITICAL", label: "Critical", min: 0, pay_pct: 0 },
    { key: "NEEDS_IMPROVEMENT", label: "Needs improvement", min: 30, pay_pct: 50 },
    { key: "MODERATE", label: "Moderate", min: 50, pay_pct: 50 },
    { key: "STRONG", label: "Strong", min: 70, pay_pct: 100 },
    { key: "EXCELLENT", label: "Excellent", min: 90, pay_pct: 100 },
  ],
  exit_review_below: 30,
  exit_review_consecutive: 2,
  kpi_weight_cap_pct: 30,
  attendance_split: { daily: 50, meeting: 25, punctuality: 25 },
  grace_minutes: 10,
  late_task_penalty_pct: 25,
  late_deliverable_penalty_pct: 30,
  late_report_credit_pct: 60,
  report_grace_days: 1,
  priority_weights: { LOW: 1, MEDIUM: 2, HIGH: 3 },
  missing_component_policy: "EXCLUDE", // EXCLUDE = leave out components with no data; ZERO = count them as 0
  attendance_alert_below_pct: 80,
  repeated_lateness_count: 3,
  unverified_alert_count: 5,
  kpi_missed_below_pct: 70,
  enforce_payroll_approval: true,
  attendance_enabled: true, // set to false when staff work remotely: hides attendance everywhere and re-balances the other score weights
};

// Existing role text (lower-cased) -> office. suggested=true means "show to management, never apply automatically".
const TITLE_MAP = [
  ["pa", "PERSONAL_ASSISTANT"], ["personal assistant", "PERSONAL_ASSISTANT"],
  ["tech operations manager", "TECH_OPS"], ["tech operations", "TECH_OPS"],
  ["creative director", "CREATIVE_DIRECTOR"], ["content creator", "CONTENT_CREATOR"],
  ["social media manager", "SOCIAL_MEDIA"], ["social media & community manager", "SOCIAL_MEDIA"],
  ["research & partnership", "ORPI"], ["research & partnerships", "ORPI"], ["research, partnerships & innovation", "ORPI"], ["orpi", "ORPI"],
  ["project manager", "PROJECT_MANAGER"],
  ["assistant program manager", "PROJECT_MANAGER", true], ["assistant project manager", "PROJECT_MANAGER", true],
];

module.exports = { OFFICES, GENERAL_STANDARD, DEFAULT_SETTINGS, TITLE_MAP };
